version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: node_modules/
          # Must be relative path from root
          paths:
            - "*"
  test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - attach_workspace:
          at: node_modules/
      - run:
          name: Run Tests
          command: npm run test:unit
  eslint:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - attach_workspace:
          at: node_modules/
      - run:
          name: Run Linting
          command: npm run lint

workflows:
  main:
    jobs:
      - build
      - test:
          requires: 
            - build
      - eslint:
          requires: 
            - build
